#!/bin/sh /etc/rc.common
# Copyright (c) 2011-2015 OpenWrt.org

START=90
STOP=15

NAME=sdns



uci_get_by_type() {
	local ret=$(uci get $NAME.@$1[0].$2 2>/dev/null)
	echo ${ret:=$3}
}

start(){


	local dns1=$(uci_get_by_type sdns dns1)
        local dns2=$(uci_get_by_type sdns dns2)
  
	sed -i '/no-resolv/d' /etc/dnsmasq.conf 
        sed -i '/no-poll/d' /etc/dnsmasq.conf 
        sed -i '/server=/d' /etc/dnsmasq.conf 
     
        local DNS_enabled=$(uci_get_by_type sdns dns_enabled)
	if [ "$DNS_enabled" = "1" ]; then
cat >> /etc/dnsmasq.conf <<EOF
no-resolv
no-poll
server=$dns1
server=$dns2
EOF

	fi

        /etc/init.d/dnsmasq restart
}

stop(){
	/etc/init.d/dnsmasq restart
}
