#!/bin/sh /etc/rc.common

START=80

restart()
{                                                                                                       
	/usr/sbin/dnspod restart
}

start()
{
	/usr/sbin/dnspod start
}

stop()
{
	/usr/sbin/dnspod stop
}
