#!/bin/sh

uci set luci.main.lang=zh_cn
uci set luci.main.mediaurlbase=/luci-static/advanced
uci commit luci


uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

ci set upnpd.@upnpd[0].enabled=1
uci commit upnpd

uci set fstab.@global[0].anon_mount=1
uci commit fstab

uci set dropbear.@dropbear[0].Interface="lan"
uci commit dropbear

#uci set firewall.@defaults[0].flow_offloading=1
#uci set firewall.@defaults[0].flow_offloading_hw=1
#uci commit firewall




ln -sf /sbin/ip /usr/bin/ip

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

sed -i 's/downloads.openwrt.org/openwrt.proxy.ustclug.org/g' /etc/opkg/distfeeds.conf
sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow

sed -i "s/# //g" /etc/opkg/distfeeds.conf


cat > /etc/rc.local <<EOF
# Put your custom commands here that should be executed once
# the system init finished. By default this file does nothing.
ifconfig eth0 down;ifconfig eth0 hw ether d6:57:a9:96:e6:f5;ifconfig eth0 up
exit 0
EOF
sh /etc/rc.local


cat > /etc/config/wireless  <<EOF
config wifi-device 'radio0'
	option type 'mac80211'
	option channel 'auto'
	option hwmode '11g'
	option path 'pci0000:00/0000:00:01.0/0000:02:00.0'
	option htmode 'HT20'
	option txpower '20'
	option legacy_rates '1'
	option country 'CN'

config wifi-iface 'default_radio0'
	option device 'radio0'
	option network 'lan'
	option mode 'ap'
	option ssid 'OpenWrt'
	option encryption 'psk2'
	option key 'liu1987A'

config wifi-device 'radio1'
	option type 'mac80211'
	option hwmode '11a'
	option path 'pci0000:00/0000:00:00.0/0000:01:00.0'
	option htmode 'VHT80'
	option legacy_rates '1'
	option country 'CN'
	option channel '161'

config wifi-iface
	option device 'radio1'
	option mode 'ap'
	option ssid 'OpenWrt-5G'
	option network 'lan'
	option encryption 'psk2'
	option key 'liu1987A'

EOF

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
wifi up

sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
echo "iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user
echo "iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user

exit 0



