#!/bin/sh
echo "$(date "+%F %T"): 正在下载adblockplus规则..."
/usr/bin/wget --quiet --no-check-certificate https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt -O /tmp/adlist.txt
if [ "$?" == "0" ]; then
	grep ^\|\|[^\*]*\^$ /tmp/adlist.txt | sed -e 's:||:address\=\/:' -e 's:\^:/0\.0\.0\.0:' > /tmp/dnsmasq.adblock
	rm -f /tmp/adlist.txt
	sed -i '/youku/d' /tmp/dnsmasq.adblock >/dev/null 2>&1
	sed -i '/[1-9]\{1,3\}\.[1-9]\{1,3\}\.[1-9]\{1,3\}\.[1-9]\{1,3\}/d' /tmp/dnsmasq.adblock >/dev/null 2>&1
	echo "$(date "+%F %T"): adblockplus规则转换完成，开始校验..."
	if [ -f "/usr/share/koolproxy/dnsmasq.adblock" ]; then
		diff /tmp/dnsmasq.adblock /usr/share/koolproxy/dnsmasq.adblock >/dev/null
		[	 $? = 0 ] && echo "$(date "+%F %T"): adblockplus本地规则和服务器规则相同，无需更新!" && rm -f /tmp/dnsmasq.adblock && exit
	fi
	echo "$(date "+%F %T"): 检测到adblockplus规则有更新，开始应用新规则！"
	mv /tmp/dnsmasq.adblock /usr/share/koolproxy/dnsmasq.adblock
	cp -f /usr/share/koolproxy/dnsmasq.adblock /etc/dnsmasq.d/dnsmasq.adblock
	[ -f "/etc/dnsmasq.d/dnsmasq.adblock" ] && ln -sf /etc/dnsmasq.d/dnsmasq.adblock /tmp/dnsmasq.d/dnsmasq.adblock
	/etc/init.d/dnsmasq restart >/dev/null 2>&1
	echo "$(date "+%F %T"): adblockplus规则更新完成！"
else
	echo "$(date "+%F %T"): 获取在线版本时出现错误! "
	[ -f /tmp/adlist.txt ] && rm -f /tmp/adlist.txt
fi
